version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: balance_service
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: inventory_service
    ports:
      - "3310:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql